### ISSUE TITLE
[PE-D][Tester D] Name field does not accept symbols

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-4/tp#193] opened 2022-10-28 17:46 UTC
Name does not accept symbols such as "," or "/" even though they are a valid part of names.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jetlfj/ped#1

**Comment by NicholasTYD** [comment] 2022-10-29 07:08
Seems like a duplicate of #222.

I propose that we close this issue

**Closed** 2022-10-30 13:21 UTC
