### ISSUE TITLE
[PE-D][Tester A] hide patient command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-4/tp#199] opened 2022-10-28 18:15 UTC
![Screenshot 2022-10-28 at 4.25.17 PM.png](https://raw.githubusercontent.com/Evande1/ped/main/files/0dba8cc4-897e-4250-b1eb-23b94a97d368.png)

Able to hide nothing with an empty tag? 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Evande1/ped#3

**Comment by NicholasTYD** [comment] 2022-10-29 07:18
Seems like a duplicate of #197 

I propose we close this issue

**Closed** 2022-10-30 15:05 UTC
